// AUTOGENERATED
export default [
  "img/con.jpg",
  "img/fconcrete.jpg",
  "img/grunge.jpg",
  "img/hahnemuhle.jpg",
  "img/lightgray.jpg",
  "img/lj.jpg",
  "img/pizza.jpg",
  "img/watercolor.jpg",
  "img/white.jpg",
  "img/wm.jpg",
];
