import { readdirSync, writeFileSync } from "fs"
import { resolve } from "path"
import * as url from 'url';

async function main() {
  const list = readdirSync(resolve(__dirname, "../", "img")).filter(file => /\.(png|jpe?g|gif|webp)$/.test(file)).map(file => `img/${file}`)
  writeFileSync(resolve(__dirname, "../", "src", "list.ts"), `// AUTOGENERATED\nexport default ${JSON.stringify(list)}`)
  console.info("Written list.js")
}

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

main().catch(e => console.error(e))